FROM yg397/openresty-thrift:xenial
# RUN ln -sf /dev/stdout /usr/local/openresty/nginx/logs/access.log \
#    && ln -sf /dev/stderr /usr/local/openresty/nginx/logs/error.log
COPY nginx.conf /usr/local/openresty/nginx/conf/nginx.conf 
