version: "3"
services:
#   Enables resolving container hostnames from host machine
  dns-media:
    image: defreitas/dns-proxy-server
    volumes:
      - /opt/dns-proxy-server/conf:/app/conf
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/resolv.conf:/etc/resolv.conf

  nginx-web-server-dynamic:
    # image: yg397/openresty-thrift:xenial
    image: 050bdfa99a77 
    hostname: nginx-thrift-backup-1
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ./nginx-web-server/lua-scripts:/usr/local/openresty/nginx/lua-scripts
      - ./nginx-web-server/new_docker/nginx_iwlc.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./nginx-web-server/jaeger-config.json:/usr/local/openresty/nginx/jaeger-config.json
      - ./gen-lua:/gen-lua
      - ./source/iterate.lua:/usr/local/iterate.lua
      - ./source/nodes.lua:/usr/local/nodes.lua
      - ./source/two_choices.lua:/usr/local/two_choices.lua
      - ./source/iwlc.lua:/usr/local/iwlc.lua

  nginx-web-server:
    image: yg397/openresty-thrift:xenial
    hostname: nginx-thrift
    ports:
      - 8081:8080
    restart: always
    volumes:
      - ./nginx-web-server/lua-scripts:/usr/local/openresty/nginx/lua-scripts
      - ./nginx-web-server/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./nginx-web-server/jaeger-config.json:/usr/local/openresty/nginx/jaeger-config.json
      - ./gen-lua:/gen-lua


  jaeger:
    image: jaegertracing/all-in-one:latest
    hostname: jaeger
    ports:
#      - 5775:5775/udp
#      - 6831:6831/udp
#      - 6832:6832/udp
#      - 5778:5778
      - 16686:16686
#      - 14268:14268
#      - 9411:9411
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
